name: 'Calibre-Web Smoke test with IIAB install'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Turn off ACLs in /opt/iiab, for clean clone to /opt/iiab/iiab (chmod permissions preserved)
        run: |
          sudo mkdir /opt/iiab         # Not needed by git clone, but allows for setfacl removal of ACLs (drwxrwxrwx+) inherited from runner's /opt
          sudo setfacl -b /opt/iiab    # Turn off ACLs, reverting to chmod UNIX permissions -- to cleanly preserve chmod throut tree (unlike chmod -R 755 override of 777)
          sudo git clone https://github.com/iiab/iiab /opt/iiab/iiab
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          sudo mkdir /etc/iiab
          sudo cat > local_vars.yml << EOF
          calibreweb_install: True
          calibreweb_enabled: True
          calibreweb_repo_url: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          calibreweb_version: $GITHUB_REF_NAME
          nodocs: True
          kolibri_install: False
          kolibri_enabled: False
          kiwix_install: False
          kiwix_enabled: False
          osm_vector_maps_install: False
          awstats_install: False
          awstats_enabled: False
          matomo_install: False
          matomo_enabled: False
          captiveportal_install: False
          network_install: False
          network_enabled: False
          admin_console_install: False
          admin_console_enabled: False
          EOF
          mv local_vars.yml /etc/iiab
          ls -l /etc/iiab/local_vars.yml
          cat /etc/iiab/local_vars.yml
      - run: sudo /opt/iiab/iiab/scripts/ansible    # Install Ansible
      - run: sudo ./iiab-install                    # Install IIAB Calibre-Web!
        working-directory: /opt/iiab/iiab
